spring.application.name=SpringActuators

# To expose all end points (common in dev, risky in production environment!)
management.endpoints.web.exposure.include=*

# To expose only specific ones
#management.endpoints.web.exposure.include=health,info,metrics

management.endpoint.shutdown.enabled=true
